apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: varnishservices.icm.ibm.com
spec:
  group: icm.ibm.com
  names:
    kind: VarnishService
    plural: varnishservices
  scope: Namespaced
  subresources:
    scale:
      specReplicasPath: .spec.deployment.replicas
      statusReplicasPath: .status.deployment.replicas
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            deployment:
              properties:
                affinity:
                  type: object
                container:
                  properties:
                    image:
                      type: string
                    imagePullPolicy:
                      type: string
                    imagePullSecret:
                      type: string
                    livenessProbe:
                      type: object
                    readinessProbe:
                      type: object
                    resources:
                      type: object
                    restartPolicy:
                      type: string
                    varnishArgs:
                      items:
                        type: string
                      type: array
                  required:
                  - image
                  - imagePullSecret
                  type: object
                replicas:
                  format: int32
                  type: integer
                tolerations:
                  items:
                    type: object
                  type: array
              type: object
            logFormat:
              type: string
            logLevel:
              type: string
            podDisruptionBudget:
              type: object
            service:
              properties:
                prometheusAnnotations:
                  type: boolean
                varnishExporterPort:
                  type: object
                varnishPort:
                  type: object
              type: object
            vclConfigMap:
              properties:
                entrypointFile:
                  type: string
                name:
                  type: string
              required:
              - name
              - entrypointFile
              type: object
          required:
          - vclConfigMap
          - deployment
          - service
          type: object
        status:
          properties:
            deployment:
              type: object
            service:
              properties:
                cached:
                  properties:
                    ip:
                      type: string
                    loadBalancer:
                      type: object
                    name:
                      type: string
                  type: object
                noCached:
                  properties:
                    ip:
                      type: string
                    loadBalancer:
                      type: object
                    name:
                      type: string
                  type: object
              type: object
            vcl:
              properties:
                availability:
                  type: string
                configMapVersion:
                  type: string
                version:
                  type: string
              required:
              - configMapVersion
              - availability
              type: object
          required:
          - vcl
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
