apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: varnishclusters.ibm.com
spec:
  validation:
    openAPIV3Schema:
      properties:
        metadata:
          properties:
            name:
              # limit name to 40 chars due to k8s length limits
              type: string
              maxLength: 40