required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
]

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.2"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.10.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.2"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.10.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.5"

[[constraint]]
  name = "github.com/caarlos0/env"
  version = "v3.2.0"

[[constraint]]
  name = "github.com/juju/errors"
  branch = "master"

  [[constraint]]
    name = "github.com/json-iterator/go"
    version = "1.1.4"
  
  