required = [
  "k8s.io/code-generator/cmd/client-gen"
]

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.2"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.10.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.2"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.10.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.5"

[[constraint]]
  name = "github.com/caarlos0/env"
  version = "v3.2.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false
    go-tests = false

  # honestly no idea why this is necessary, but it is
  # see https://github.com/kubernetes/sample-controller/issues/6
  [[prune.project]]
    name = "k8s.io/gengo"
    unused-packages = false
    non-go = false
    go-tests = false