apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: varnishservices.icm.ibm.com
spec:
  group: icm.ibm.com
  names:
    kind: VarnishService
    listKind: VarnishServiceList
    plural: varnishservices
    singular: varnishservice
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: icm-varnish-k8s-operator/operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: icm-varnish-k8s-operator/operator
  template:
    metadata:
      labels:
        name: icm-varnish-k8s-operator/operator
    spec:
      containers:
        - name: icm-varnish-k8s-operator/operator
          image: varnish-service:v0.0.1
          command:
          - icm-varnish-k8s-operator/operator
          imagePullPolicy: Always
