# namespace should match the Namespace created in the Getting Access section of the README.md
namespace: kube-system
# this field should not be changed
namePrefix: varnish-service-

# Run multiple instances of the operator, and if one goes down, have another seamlessly replace it
leaderElection:
  # if set to false, only 1 pod will be created
  enabled: true
  # name of the ConfigMap used to determine leader
  id: varnish-operator-lock
  # Number of pods running operator, if .leaderElection.enabled == true.
  replicas: 2
container:
  # path to image + tag
  image: us.icr.io/icm-varnish/varnish-controller:0.14.4
  # If secret is needed, use the name of the imagePullSecret created in the Getting Access section of the README.md
# imagePullSecret: docker-reg-secret
  # imagePullPolicy is passed directly to the varnish deployment, that controls how the varnish image will be pulled for new containers
  imagePullPolicy: Always
  # restart policy used for Varnish containers
  restartPolicy: Always
  # it is unlikely you will need to change the resources values of the operator
  resources:
    limits:
      cpu: 500m
      memory: 200Mi
    requests:
      cpu: 500m
      memory: 200Mi
  # port on which to expose operator metrics
  metricsPort: 8080
  # port on which to expose webhook. Unlikely to need to change this
  webhookPort: 9244

# logging level: "debug", "info", "warn", "error"
logLevel: info
# logging encoder: "json", "console"
logFormat: json
