# namespace should match the Namespace created in the Getting Access section of the README.md
namespace: varnish-operator-system
# this field should not be changed
namePrefix: varnish-service-

# Specifies the pod count of the Manager. Default value is 2 replicas for HA
replicas: 2
# Run multiple instances of the operator, and if one goes down, have another seamlessly replace it
leaderElection:
  enabled: true
  id: varnish-operator-lock
container:
  # path to image + tag
  image: us.icr.io/icm-varnish/varnish-controller:0.13.4
  # Use the name of the imagePullSecret created in the [Getting Access](#getting-access) section above
  imagePullSecret: docker-reg-secret
  # imagePullPolicy is passed directly to the varnish deployment, that controls how the varnish image will be pulled for new containers
  imagePullPolicy: Always
  # restart policy used for Varnish containers
  restartPolicy: Always
  # it is unlikely you will need to change the resources values of the operator
  resources:
    limits:
      cpu: 500m
      memory: 200Mi
    requests:
      cpu: 500m
      memory: 200Mi
  # port on which to expose operator metrics
  metricsPort: 8080
  # port on which to expose webhook
  webhookPort: 9244

# logging level: "debug", "info", "warn", "error"
logLevel: info
# logging encoder: "json", "console"
logFormat: json
