# Number of pods running the operator
replicas: 1
container:
  # path to image + tag
  image: us.icr.io/icm-varnish/varnish-operator:0.22.1
  # If secret is needed, use the name of the imagePullSecret created in the Getting Access section of the README.md
# imagePullSecret: docker-reg-secret
  # imagePullPolicy is passed directly to the varnish deployment, that controls how the varnish image will be pulled for new containers
  imagePullPolicy: Always
  # restart policy used for Varnish containers
  restartPolicy: Always
  # it is unlikely you will need to change the resources values of the operator
  resources:
    limits:
      cpu: 500m
      memory: 200Mi
    requests:
      cpu: 500m
      memory: 200Mi
# logging level: "debug", "info", "warn", "error"
logLevel: info
# logging encoder: "json", "console"
logFormat: json
