name: Tests

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Setup-go installation
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=2m --enable exportloopref
          skip-pkg-cache: true
          skip-build-cache: true
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.17
      id: go
    - name: Setup Kubebuilder assets
      run: |
        curl -sSLo envtest-bins.tar.gz "https://storage.googleapis.com/kubebuilder-tools/kubebuilder-tools-1.24.2-linux-amd64.tar.gz"
        mkdir -p /tmp/kubebuilder
        tar -C /tmp/kubebuilder/ --strip-components=1 -zvxf envtest-bins.tar.gz
        rm envtest-bins.tar.gz;
        echo "KUBEBUILDER_ASSETS=/tmp/kubebuilder/bin" >> $GITHUB_ENV
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Get dependencies
      run: go mod download
    - name: Unit tests
      run: |
        go test github.com/ibm/varnish-operator/pkg/... github.com/ibm/varnish-operator/cmd/... github.com/ibm/varnish-operator/api/... -coverprofile cover.out
